import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Clerk Authentication
import {
  ClerkProvider,
} from '@clerk/nextjs'
import AppHeader from "@/components/header/AppHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className + "font-sans"}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
